### ISSUE TITLE
Script stuck on Auto updating

### ISSUE THREAD

**Issue by Tommatheussen** [mrworf/plexupdate#76]
It seems the script is stuck at auto updating, I always get "Auto updating...OK" out from the script, multiple times after each other (seems like it never moves on to the next phase).

Playing around with some stuff I first thought it was because I had my config and log file moved into the same folder, but when I remove the location of my .plexupdate file from the command, it seems to be working just fine again.

Also disabling Auto update in the config file, and specifying the config's location does work.

EDIT: After some more investigating, it seems that the problem originates from here: https://github.com/mrworf/plexupdate/blob/master/plexupdate.sh#L233

this is the log I get when I print out the ALLARGS variable: 
```
Auto updating...OK
../.plexupdate
Auto updating...OK
../.plexupdate -U
Auto updating...OK
../.plexupdate -U -U
Auto updating...OK
../.plexupdate -U -U -U
Auto updating...OK
../.plexupdate -U -U -U -U
Auto updating...OK
../.plexupdate -U -U -U -U -U
```

**Comment by Tommatheussen** [comment]
After some more checking it seems it's related to #75
You can try using the -r flag, to print to url, which doesn't work either. So it seems any flag is just ignored when specifying the config location

**Comment by mrworf** [comment]
Solved with latest update, please try and close issue if confirmed.

**Comment by Tommatheussen** [comment]
hmm, I'm not sure, I get some weird and unstable behaviour.
I'll put a few scenario's here so you can check:

- Config file in home folder:
  - Not specifying config or arguments: Runs fine
  - Specifying config only: Works fine
  - Specifying arguments:
    - -r: Doesn't seem to use that command, just goes on to next phase(checking system version)
    - -U: Does work, not being auto updated
  - Specifying both config and arguments:
    - Config first:
      - -r: This one works now, prints and exits
      - -U: This one doesn't, still does the auto updating check
      - Both: Only -r gets respected
    - Config last:
      - -r: Does not work anymore
      - -U: Works, does not auto update
      - Both: This does work, not updating and printing url

- Config in same folder as script:
  - Specifying config only: Starts with auto updating, then fails: Doesn't take the values from the config, error on username/password
  - Specifying both config and arguments:
    - Config first:
      - Any argument: Same behaviour with only config specified, except it's not auto updating either
    - Config last:
      - -r: Processing starts again, yet argument does not get processed (not printing)
      - -U: Processing start again, not auto updating (so correct)
      - Both: Processing correct now

- Config in different location: Exactly the same as config in same folder.

As you can see it has quite some different behaviours, I didn't test with all possible arguments.
I am currently using `plexupdate.sh -r .plexupdate` command, since this ignores the -r command and processes the rest of the system correctly.

I hope this helps a bit find what could be the issue, it seems that only when -U is present, the other arguments are getting processed, not entirely sure about that though

**Comment by mrworf** [comment]
I was testing that specifically yesterday and it seemed to work fine, but I could very well have missed something. Config file last is critical because it specifically assumes that the filename is last, it won't look anywhere else. I will review it when I get home from work, thanks for giving this feedback, it's very valuable to me. 

Sorry for the mess.

**Comment by mrworf** [comment]
Were you running this using SUDO?

**Comment by Tommatheussen** [comment]
Yes, all command where run with sudo (since I have autoinstall in my config)

**Comment by mrworf** [comment]
Please pull and try again, it seems that I made a slight error when using auto update and it wouldn't properly retain the provided arguments.

Config HAS to be last or it will never work, putting it first will not only stop processing of arguments, it will also ignore the config file. Not ideal, should really give you an error code, but I don't have time today to correct this.

All other things should work now, but please test and close if confirmed

Thanks

**Comment by blackley** [comment]
mr wolf i have just done a pull now and the update problem is still an issue...

**Comment by mrworf** [comment]
@blackley Can you please provide a bit more detail than that ? :) Like, what exactly goes wrong and what arguments are you running it with and what do you have in the config file. I'm unable to reproduce any error on my end right now, so it would help a lot if you could help me out.

**Comment by mrworf** [comment]
Nevermind, I just hit it myself (darn it)

**Comment by blackley** [comment]
are sorry

run the script with -u and get

Auto updating...OK
Auto updating...OK
Auto updating...OK
Auto updating...OK
Auto updating...OK
Auto updating...OK
Auto updating...OK
...

and it goes on until you cancel it.

**Comment by mrworf** [comment]
Found that issue now, finally, but still some odd behaviors going on. Will update in a little while. Thanks for bearing with me.

**Comment by mrworf** [comment]
Pushed another update, please try. Now the darn array should work as I expect it to.

**Comment by mrworf** [comment]
As an added bonus, -r -q now works as one would have expected

**Comment by blackley** [comment]
Latest update has resolved the problem - thanks :-)

**Comment by mrworf** [comment]
@Tommatheussen @blackley thanks for the patience. @Tommatheussen Please close the issue once you've confirmed it on your system, but given @blackley 's results, I'm fairly confident that I got it good this time :v:

**Comment by Tommatheussen** [comment]
@mrworf confirmed that it works, thanks man :)
